### ISSUE TITLE
Verify that Primality is deterministic in the interval [0;2^64]

### ISSUE THREAD

**Issue by JASory** [JASory/ENT#3]
Currently Number-Theory's claim of determinism is reliant on Forisek & Jancina's  (erroneous) claim of determinism in there original implementation. However it is known that there is at least one error (677 is passed as composite) in the original table, so while it is likely that the claim is true this is not verified, and it is a major goal of the Rust-CAS team to prove it. 

Currently it has been proven that is_prime is deterministic in the interval [0;2^41]*.  If you plan on contributing to verification; post the interval you are checking in, the number of cores used (not the total cores but rather the number of threads that are being used for verification), and the processor model. It is important to post as soon as you start verification to prevent others from utilizing time verifying the same interval. We show an example below. 

First post
<pre>
Processor              Threads            Interval   
i3-4005u                   1                  [2^33;2^34]
</pre>
When you finish the computation
<pre>
Count                  Time     
 717267168          10829.22159s
 </pre>

Or more tragically 
<pre>
Failure     Reason 
</pre>
To allow others to know if they need to duplicate it. 

One thing to note is that it is important to choose an interval that is divisible by the number of processors used with no remainder to prevent any potential truncation. 

Start checking at 2^41. 

*This value will be continously updated so check first.

**Comment by Pencilcaseman** [comment]
```
  Processor              Threads            Interval   
ryzen9 3950x               16              [2^40;2^41]

     Count                     Time     
39113482640      35887.077132s
```

**Comment by JASory** [comment]
Proven utilizing Jan Feitsma's base-2 pseudoprime list.
