### ISSUE TITLE
nth_prime buggy

### ISSUE THREAD

**Issue by DanielFabian** [JASory/ENT#5]
Looks like a off-by-one error in the hard-coded prime list:

```rust
use number_theory::NumberTheory;

pub fn nth_prime(n: u32) -> u32 {
    n.nth_prime().unwrap()
}

#[cfg(test)]
mod bug_repro {
    use super::*;

    #[test]
    fn bug_repro() {
        assert_eq!(nth_prime(1), 2);
    }
}
```

**Comment by DanielFabian** [comment]
(for big enough `n`, it behaves correctly since it sieves there). But for the small indices, it is off by one, apparently. We should really be indexing the list at `n - 1`. But I can't pass 0 since there's an assertion that `n > 0`. And also the algos later seem to assume 1-based indexing of primes.

**Comment by DanielFabian** [comment]
root cause seems to be this line which is inconsistent with 1-based indexing: https://github.com/JASory/ENT/blob/fca294f26e920f3a74cf3d704560d39b17905ef9/src/primitive/byte.rs#L136

**Comment by JASory** [comment]
`nth_prime` doesn't actually sieve it sequentially enumerates, `pi` (prime-counting) and `prime_list` do sieve, but nth_prime will sieve in the future. Anyway this is fixed now, but only in the repository. I have some time dedicated in the relatively near future to expanding the functionality and fixing minor issues like this, which will then get uploaded as 0.0.24.
